package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IApplicationRepository;
import dao.uow.IUnitOfWork;
import domain.model.Application;
import domain.model.History;

public class ApplicationRepository extends RepositoryBase<Application> 
implements IApplicationRepository{
	
	public ApplicationRepository(Connection connection, 
			IMapResultSetIntoEntity<Application> mapper, IUnitOfWork uow) {
		super(connection, mapper, uow);
	}
	
	@Override
	protected String createTableSql() {
		return "CREATE TABLE application("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "date varchar(50),"
				+ "price varchar(50)," 
				+ "FOREIGN KEY (CUSTOMER_FROM_ID) REFERENCE customer(id),"
				+ "FOREIGN KEY (SERVICE_FROM_ID) REFERENCE service(id),"
				+ "FOREIGN KEY (EMPLOYEE_FROM_ID) REFERENCE employee(id),"
				+ "FOREIGN KEY (HARDWARE_FROM_ID) REFERENCE hardware(id),"
				+ ")";
	}
	
	@Override
    protected String tableName() {
        return "Application";

    }
	
	 @Override
	    protected String insertSql() {
	        return "INSERT INTO application("
	                + "date, price,"
	                + "CUSTOMER_FROM_ID,"
	                + "SERVICE_FROM_ID,"
	                + "EMPLOYEE_FROM_ID"
	                + "HARDWARE_FROM_ID"
	                + ") VALUES (?,?)";
	    }
	 
	 @Override
	    protected String updateSql() {
	        return "UPDATE Application SET (date, price, CUSTOMER_FROM_ID" +
	                ", SERVICE_FROM_ID, EMPLOYEE_FROM_ID, HARDWARE_FROM_ID)= (?,?) WHERE id = ?";
	    }
	 
	 @Override
	    protected void setUpdate(Application application) throws SQLException {
	        update.setDate(1, application.getDate());
	        update.setString(2, application.getPrice());
	        update.setInt(3, application.getFromServiceId());
	        update.setInt(4, application.getFromCustomerId());

	    }

	    @Override
	    protected void setInsert(Application application) throws SQLException {
	        insert.setDate(1, application.getDate());
	        update.setString(2, application.getPrice());
	        update.setInt(3, application.getFromServiceId());
	        update.setInt(4, application.getFromCustomerId());
	    }
}
