package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IApplicationRepository;
import dao.uow.IUnitOfWork;
import domain.model.Application;
import domain.model.Customer;
import domain.model.Employee;
import domain.model.Hardware;
import domain.model.Service;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;

public class ApplicationRepository extends RepositoryBase<Application>
implements IApplicationRepository{


    public ApplicationRepository(Connection connection,
			IMapResultSetIntoEntity<Application> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);

    }

    @Override
    protected String createTableSql() {
		return "CREATE TABLE application("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "date varchar(50),"
				+ "price varchar(50)," 
				+ "FOREIGN KEY (CUSTOMER_ID) REFERENCE customer(id),"
				+ "FOREIGN KEY (SERVICE_ID) REFERENCE service(id),"
				+ "FOREIGN KEY (EMPLOYEE_ID) REFERENCE employee(id),"
				+ "FOREIGN KEY (HARDWARE_ID) REFERENCE hardware(id),"
				+ ")";
    }

    @Override
    protected String tableName() {
        return "Application";

    }

    @Override
    protected String insertSql() {
    	return "INSERT INTO application("
                + "date, price,"
                + "CUSTOMER_ID,"
                + "SERVICE_ID,"
                + "EMPLOYEE_ID"
                + "HARDWARE_ID"
                + ") VALUES (?,?)";
    }

    @Override
    protected String updateSql() {
    	return "UPDATE Application SET (date, price, CUSTOMER_ID" +
                ", SERVICE_ID, EMPLOYEE_ID, HARDWARE_ID)= (?,?) WHERE id = ?";
    }

    @Override
    protected void setUpdate(Application application) throws SQLException {
        update.setDate(1, application.getDate());
        update.setString(2, application.getPrice());
        update.setInt(3, application.getServiceId());
        update.setInt(4, application.getCustomerId());
        update.setInt(5, application.getEmployeeId());
        update.setInt(6, application.getHardwareId());

    }

    @Override
    protected void setInsert(Application application) throws SQLException {
        insert.setDate(1, application.getDate());
        update.setString(2, application.getPrice());
        update.setInt(3, application.getServiceId());
        update.setInt(4, application.getCustomerId());
        update.setInt(5, application.getEmployeeId());
        update.setInt(6, application.getHardwareId());
    }

	public List<Application> of(Service service) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Application> withDate(Date from, Date to) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Application> withPrice(String price) {
		// TODO Auto-generated method stub
		return null;
	}
}
