package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IHardwareRepository;
import dao.uow.IUnitOfWork;
import domain.model.Hardware;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

public class HardwareRepository extends RepositoryBase<Hardware>
implements IHardwareRepository{


    public HardwareRepository(Connection connection,
			IMapResultSetIntoEntity<Hardware> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);

    }

    @Override
    protected String createTableSql() {
		return "CREATE TABLE hardware("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(50),"
				+ "price varchar(50)," 
				+ "manufacturer varchar(50),"
				+ ")";
    }

    @Override
    protected String tableName() {
        return "hardware";

    }

    @Override
    protected String insertSql() {
    	return "INSERT INTO hardware(name, price, manufacturer) VALUES (?,?,?)";
    }

    @Override
    protected String updateSql() {
    	return "INSERT INTO hardware(name, price, manufacturer) VALUES (?,?,?) WHERE id = ?";
    }

    @Override
    protected void setUpdate(Hardware hardware) throws SQLException {
    	update.setString(1, hardware.getName());
		update.setString(2, hardware.getPrice());
		update.setString(3, hardware.getManufacturer());

    }

    @Override
    protected void setInsert(Hardware hardware) throws SQLException {
    	update.setString(1, hardware.getName());
		update.setString(2, hardware.getPrice());
		update.setString(3, hardware.getManufacturer());
    }

	public List<Hardware> withName(String name) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Hardware> withPrice(String name) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Hardware> withManufacturer(String name) {
		// TODO Auto-generated method stub
		return null;
	}
}
