package dao;

import java.sql.Connection;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IServiceRepository;
import dao.uow.IUnitOfWork;
import domain.model.Service;

public class ServiceRepository {

	public class ServiceRepository extends RepositoryBase<Service> 
	implements IApplicationRepository{
		
		public ServiceRepository(Connection connection, 
				IMapResultSetIntoEntity<Service> mapper, IUnitOfWork uow) {
			super(connection, mapper, uow);
		}
	}
	
	@Override
	protected String createTableSql() {
		return "CREATE TABLE Service("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(50),"
				+ "price varchar(50)," 
				+ ")";
	}
}
