package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IServiceRepository;
import dao.uow.IUnitOfWork;
import domain.model.Service;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

public class ServiceRepository extends RepositoryBase<Service>
implements IServiceRepository{


    public ServiceRepository(Connection connection,
			IMapResultSetIntoEntity<Service> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);

    }

    @Override
    protected String createTableSql() {
		return "CREATE TABLE service("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(50),"
				+ "price varchar(50)," 
				+ ")";
    }

    @Override
    protected String tableName() {
        return "service";

    }

    @Override
    protected String insertSql() {
    	return "INSERT INTO service(name, price) VALUES (?,?)";
    }

    @Override
    protected String updateSql() {
    	return "INSERT INTO service(name, price) VALUES (?,?) WHERE id = ?";
    }

    @Override
    protected void setUpdate(Service service) throws SQLException {
    	update.setString(1, service.getName());
		update.setString(2, service.getPrice());

    }

    @Override
    protected void setInsert(Service service) throws SQLException {
    	update.setString(1, service.getName());
		update.setString(2, service.getPrice());
    }

	public List<Service> withName(String name) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Service> withPrice(String price) {
		// TODO Auto-generated method stub
		return null;
	}

}
